# Facebook (+ Wit)
ACCESS_TOKEN = 'EAAa5mZB0BiPEBAHk5ymFx2QmKdEN540HDMSGQ0wMcrgL9EcQhPpgRZAjzT5YnY3oTVnwJ3uPXPJnPICLvKpZAJ6LYwL6Ydg0N3so6GYEPktddf7VCAs28ZATnDHD6KQgwoFUsWsuDjecx2PkluGm5wmsrNgbCXgKjWxiGYL1bQZDZD'
VERIFY_TOKEN = '<<VERIFY_TOKEN>>'

