"""empty message

Revision ID: 7d0069b03a8e
Revises: 5cc921360fae
Create Date: 2017-07-23 00:47:30.280000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0069b03a8e'
down_revision = '5cc921360fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('liked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'liked')
    # ### end Alembic commands ###
