"""empty message

Revision ID: 7dd1d44663ee
Revises: a48cba86130c
Create Date: 2017-07-03 00:57:26.489000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd1d44663ee'
down_revision = 'a48cba86130c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('interests', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'interests')
    # ### end Alembic commands ###
