"""empty message

Revision ID: 8f45d58df3c4
Revises: 
Create Date: 2017-06-14 20:56:02.768000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f45d58df3c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_chats_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('pic_url', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiting_list_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('interest', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waiting_list_user')
    op.drop_table('user')
    op.drop_table('active_chats_user')
    # ### end Alembic commands ###
