"""empty message

Revision ID: a44bfe9b9348
Revises: aa660eb2f8f7
Create Date: 2017-06-24 17:10:05.287000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44bfe9b9348'
down_revision = 'aa660eb2f8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('messages', sa.String(length=2000), nullable=True))
    op.add_column('user', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('user', 'messages')
    # ### end Alembic commands ###
