"""empty message

Revision ID: aa660eb2f8f7
Revises: ab134711410a
Create Date: 2017-06-17 02:15:42.833000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa660eb2f8f7'
down_revision = 'ab134711410a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_chats_user', 'alias',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('active_chats_user', 'partner',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_chats_user', 'partner',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('active_chats_user', 'alias',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
